language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio run
deploy:
  provider: releases
  api_key:
    secure: GIqxlnH/CL0/+j1bevltukcmTOxN3CKhk/esCIBTRhyOcsiISHBx/GCmGQHt7Xtf7Ek4fus8qHszaa2xGoEwMJgFag+qEhUg/p+FCl4a0V13rVwDPUM5xXieNDMjjMs5YNujI9/gV3fEzxabwI2PaGunBoflXoK715rwxLsWC9TmfWSnEOH/W5ece/0shj1+FJCNkS35O9sHmbJoaA8lFOVIgxH2clqKH2ip+4/QeK/JqLKe5gjzoatqIMx2/Ne7rNK1kg6eonQqF1JtfcQLdekwnEfE9fcD4nwE5M/M7YOiH2aALwNGOjQZJfOaP9US5ivD3nWBFJgGWLAUZPykoIbiPTjh/b5xZhKTJF7p52C1UqHxYPvAM32HC0DK5n+PNy6DrtsFrrtsXFXiZMCgs9ZsOlxGDUhRMyjI9CEWq+hP8nn1PBFLXW6kANF8as4O8SrzAsKuf2EepopCL/wrsn200hBo9BvcvX7Q7EKqtDvnvV6kShhRGYC4C9rmWzuDRF1h/k44lfhV+LV4oM9S+JP92T7DVOFSUfUR8a15vyCr25hdu4+qGZqwVd4In9aYqzudaE4BQyN0LooMcjoBkERaOZAvmv2g29Fyg/zZLVPBB24sBTnCJp8oqLQRY2Wt//NV5ldjA3uBMoe7wIrJlJiNEAIREY4sgkoLTQOajdg=
  file: '".pioenvs/sonoff/firmware.bin"'
  skip_cleanup: true
  on:
    tags: true
